# Generated by Django 5.0.6 on 2024-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
