# Generated by Django 5.0.6 on 2024-08-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
