# Generated by Django 5.0.6 on 2024-08-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feed_options_userreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
